typography_spectrum: 0.3403957358095795
color:
  brandStrength: 0.3975959396921098
  lightness: 0.5152810907457024
  saturation: 0.5004578353837132
  rhythmicContrast: 0.3952332129701972
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
layout_spectrum: 0.40201931167393923
author:
  name: Daniel Nauck
  email: daniel_nauck@me.com
name: danielnauck
navigation:
  - name: about
    url: 'http:danielnauck.com'
    type: external
title: Hello
description: und Danke
